SELECT
    stg_STG_PAYMENT.ID AS "ID",
    stg_STG_PAYMENT.ORDERID AS "ORDERID",
    stg_STG_PAYMENT.PAYMENTMETHOD AS "PAYMENTMETHOD",
    stg_STG_PAYMENT.STATUS AS "STATUS",
    stg_STG_PAYMENT.AMOUNT AS "AMOUNT",
    stg_STG_PAYMENT.CREATED AS "CREATED",
    stg_STG_PAYMENT._BATCHED_AT AS "_BATCHED_AT",
    stg_STG_PAYMENT.__load_date AS "__load_date",
    current_date() AS "__load_date_1"
FROM {{ref('My Location', 'stg_STG_PAYMENT')}} "stg_STG_PAYMENT"