SELECT
    STG_PAYMENT.ID AS "ID",
    STG_PAYMENT.ORDERID AS "ORDERID",
    STG_PAYMENT.PAYMENTMETHOD AS "PAYMENTMETHOD",
    STG_PAYMENT.STATUS AS "STATUS",
    STG_PAYMENT.AMOUNT AS "AMOUNT",
    STG_PAYMENT.CREATED AS "CREATED",
    STG_PAYMENT._BATCHED_AT AS "_BATCHED_AT",
    current_date() AS "__load_date"
FROM {{ref('My Location', 'STG_PAYMENT')}} "STG_PAYMENT"