name: Generate SQL files

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on push to any branch
  pull_request:
    branches:
      - '*'  # This will trigger the workflow on pull requests to any branch

permissions:
  contents: write

jobs:
  generate-sql:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: List repository contents
      run: |
        pwd
        ls -R
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r adept/requirements.txt
    
    - name: Run SQL generation script
      run: python adept/main.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add athena/models/*.sql
        git commit -m "Auto-generate SQL files" -a || echo "No changes to commit"
        git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
      env:
        PAT: ${{ secrets.PAT }}